name: Build LaTeX Reports
on:
  push:
    branches:
      - "prod"
    paths:
      - "a1/**"
      - "a2/**"
      - "a3/**"
      - "a4/**"
  workflow_dispatch:
jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            a1/report.tex
            a2/report.tex
            a3/report.tex
            a4/report.tex
            tutorial/report.tex
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
      - name: Commit report changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
